services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: multi-agent_app
    ports:
      - "80:8000"
    volumes:
      - ./app/prompts.yml:/care-llm/app/prompts.yml

    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - FIT_AZURE_API_KEY=${FIT_AZURE_API_KEY}
      - FIT_OLLAMA_API_KEY=${FIT_OLLAMA_API_KEY}
      - FIT_AZURE_API_ENDPOINT=${FIT_AZURE_API_ENDPOINT}
      - FIT_OLLAMA_API_ENDPOINT=${FIT_OLLAMA_API_ENDPOINT}
      - FIT_AZURE_API_VERSION=2024-10-01-preview
      - LLM_NAME=gpt-4o-2024-05-13
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - VALIDATOR_ENABLED=true
      - VALIDATOR_SCORE_THRESHOLD=60
      - VALIDATOR_REPEAT_COUNT=3
    depends_on:
      - redis
      - validator
    networks:
      - app-network

  validator:
    build:
      context: ./validator
      dockerfile: Dockerfile
    container_name: validation_app
    ports:
      - "8002:8002"
    networks:
      - app-network

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - /tmp/redis-chat-data:/data
      - ./redis.conf:/redis-stack.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge